name: LeetCode Sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 6"   # Runs every Saturday at 08:00 UTC

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: LeetCode Sync
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ github.token }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: leetcode
          verbose: true
          commit-header: "[LeetCode Sync]"
